jobs:
  include:
    - stage: Deploy
      language: minimal
      services:
        - docker
      env:
        - RELEASE_NUMBER=1.1.$TRAVIS_BUILD_NUMBER
      script:
        - docker build --file ./Dockerfile . --tag framebassman/izzy:$RELEASE_NUMBER
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push framebassman/izzy
      before_deploy:
        - git config --local user.name $GIT_USERNAME
        - git config --local user.email $GIT_EMAIL
        - git tag $RELEASE_NUMBER
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true

stages:
  - name: Deploy
    if: branch = master AND type != pull_request
branches:
  only:
    - /.*/
notifications:
  email: false
