# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master
trigger: 
  branches:
    include:
    - '*'

stages:
  - stage: Build_Release
    displayName: Build Docker image and push it to Docker Hub
    jobs:
    - job: Release
      pool:
        vmImage: 'ubuntu-latest'
      continueOnError: false
      steps:
      - script: |
          docker-compose \
          --project-directory=${PWD} \
          -f Deploy/docker-compose.release.yml \
          build
        displayName: Build image

      - task: Docker@2
        displayName: Push image
        inputs:
          containerRegistry: hub.docker.com
          repository: docker.io/framebassman/izzy
          command: push
          tags: $(Build.BuildNumber)
