name: Release

on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: v${{ github.run_id }}
          release_name: release_${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}