name: Release

on: push

env:
  VERSION: 1.2.${{ github.run_id }}

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: framebassman
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Sentry Release
        uses: getsentry/action-release@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: kolenka-inc
          SENTRY_PROJECT: izzy

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: framebassman/izzy:${{ env.VERSION }}

      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
