name: Release

on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: 1.1.300
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}